### ISSUE TITLE
Usage description missing - how to build?

### ISSUE THREAD

**Issue by fmauch** [bionade24/aur-ci#5]
Hi,

I am still struggling making use of this tool.

When invoking `./ci.py build ros-melodic-roscpp -v` the build fails:

```
Building ros-melodic-roscpp in ./packages/ros-melodic-roscpp
:: Synchronizing package databases...
downloading core.db...
downloading extra.db...
downloading community.db...
downloading multilib.db...
==> Making package: ros-melodic-roscpp 1.14.6-1 (Wed Aug 26 00:51:06 UTC 2020)
==> Checking runtime dependencies...
==> Installing missing dependencies...
error: target not found: ros-melodic-rostime
error: target not found: ros-melodic-xmlrpcpp
error: target not found: ros-melodic-roscpp-traits
error: target not found: ros-melodic-rosgraph-msgs
error: target not found: ros-melodic-cpp-common
error: target not found: ros-melodic-std-msgs
error: target not found: ros-melodic-rosconsole
error: target not found: ros-melodic-roscpp-serialization
error: target not found: ros-melodic-message-runtime
==> ERROR: 'pacman' failed to install missing dependencies.
```

Looking at the source code this isn't really a surprise as when using `dmakepkg` no dependencies are installed. However, as each package gets built in its own container, there's not really a chance to get them built inside this container.

Am I using it wrong? What is the intention of using this? I guess it is meant to use a package mirror containing binary releases that is in your local `/etc/pacman.conf` file?

**Comment by fmauch** [comment]
I've been playing around tonight and I got a setup working using [`makechrootpkg`](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot#Classic_way) instead of `dmakepkg`.

I configured my chroot to use a custom local repo where built packages get always stored in (not only in the case of a full deploy).

This was only playing around to make this repo useful for me for local testing, but it might be worse for using it for actual CI that way which is why I didn't make any PR, yet. My current status is on a [branch on my fork](https://github.com/bionade24/ros-aur-helpers/compare/master...fmauch:chroot). It is still at a hacky state but before further proceeding it might be interesting to hear your opinion on this @bionade24

**Comment by fmauch** [comment]
It seems like I missed [this post](https://discourse.ros.org/t/who-is-using-ros-on-archlinux/388/27) which would probably make things easier.

I think, with that I have all the info I need and was missing. I'll try to write a README and make a PR out of that if other users might go through the same learning process as I did :-)

**Comment by bionade24** [comment]
> I've been playing around tonight and I got a setup working using [`makechrootpkg`](https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_clean_chroot#Classic_way) instead of `dmakepkg`.
> 
> I configured my chroot to use a custom local repo where built packages get always stored in (not only in the case of a full deploy).
I just configured oscloud repo in it, but that is very good practice of building packages locally.
> 
> This was only playing around to make this repo useful for me for local testing, but it might be worse for using it for actual CI that way which is why I didn't make any PR, yet. My current status is on a [branch on my fork](https://github.com/bionade24/ros-aur-helpers/compare/master...fmauch:chroot). It is still at a hacky state but before further proceeding it might be interesting to hear your opinion on this @bionade24

Sorry for not responding on this that long. Yes, I hardcoded `dmakepkg` (docker-makepkg) once. Changing this to `makechrootpkg -c -r $CHROOT` is correct. Yes, it would have broken the old CI. Either you'll make a PR for it or I'll change it somewhen when I have time, where I'll additionally will add a `README.md` (Until then `ci.py -h` will tell everything.) and rename ci.py to something more fitting.  Any suggestions?

**Comment by bionade24** [comment]
I changed the default behaviour to makechrootpkg a while ago and added a README, some automatic installation of a repo is planned, additionally a intergration of repo-add.
